package gomoku;

import java.util.ArrayList;

/**
 * The MatchmakingView sends information to the MatchMakingController
 * when an action is preformed.
 * This view has two buttons, one to send an invite to another player, and
 * one for going back to the SignInView. This view also has a JList where
 * players can view players that are currently online.
 */
public class MatchmakingView extends javax.swing.JPanel {
    MatchmakingViewController vcon;
    int size = 0;
    
    /**
     * Creates new form MatchmakingView
     */
    public MatchmakingView(MatchmakingViewController vc) {
        initComponents();
        vcon = vc;
    }
    
    /**
     * Updates the list of current users online
     * @param a, the list of the users
     */
    public void updateUsers(ArrayList<String> a, String username){
        a.remove(username);
        String[] s = new String[a.size()];
        for(int i = 0; i < a.size(); i++){
            s[i] = a.get(i);
        }
        playerList.setListData(s);
    }
    
    /**
     * Holds the current list of game invites from other players within
     * an array list.
     * @param a, the list of requests a player has.
     */
    public void updateRequests(ArrayList<String> a){
        String[] s = new String[a.size()];
        for(int i = 0; i < a.size(); i++){
            s[i] = a.get(i);
        }
        requestList.setListData(s);
    }
    
    /**
     * Sets the header title for the MatchmakingView with the username of
     * the player.
     * @param name, the name of the player.
     */
    public void updateUName(String name){
        matchmakingLabel.setText("Matchmaking for: " + name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matchmakingLabel = new javax.swing.JLabel();
        playersOnlineLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList();
        sendgameButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestList = new javax.swing.JList();
        acceptButton = new javax.swing.JButton();
        declineLabel = new javax.swing.JButton();
        requestsLabel = new javax.swing.JLabel();
        boardSizeComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        matchmakingLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        matchmakingLabel.setText("Matchmaking");

        playersOnlineLabel.setText("Players Online:");

        jScrollPane1.setViewportView(playerList);

        sendgameButton.setText("Send Game Invite");
        sendgameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendgameButtonActionPerformed(evt);
            }
        });

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(requestList);

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        declineLabel.setText("Decline");
        declineLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineLabelActionPerformed(evt);
            }
        });

        requestsLabel.setText("Requests:");

        boardSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "15x15", "20x20", "25x25", "30x30", "35x35" }));
        boardSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardSizeComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Board Size:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendgameButton)
                            .addComponent(matchmakingLabel)
                            .addComponent(playersOnlineLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(acceptButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(declineLabel))
                    .addComponent(requestsLabel)
                    .addComponent(boardSizeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchmakingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playersOnlineLabel)
                    .addComponent(requestsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendgameButton)
                    .addComponent(acceptButton)
                    .addComponent(declineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton)
                    .addComponent(boardSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     *
     * @param evt, when the sendInvite button is chosen by the player.
     */
    private void sendgameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendgameButtonActionPerformed
        String selected = playerList.getSelectedValue().toString();
        vcon.sendInvite(selected);
    }//GEN-LAST:event_sendgameButtonActionPerformed
    
    /**
     * Calls the menuBtn method within the MatchmakingViewController
     * @param evt, when the menu button is chosen by the player.
     */
    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        vcon.logOff();
        vcon.menuBtn();
    }//GEN-LAST:event_menuButtonActionPerformed
    
    /**
     * Calls the acceptInvite method within the MatchmakingViewController
     * @param evt, when the accept button is chosen by the player.
     */
    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        int boardSize = boardSizeComboBox.getSelectedIndex();
        if(boardSize == 0){
            size = 15;
        }
        if(boardSize == 1){
            size = 20;
        }
        if(boardSize == 2){
            size = 25;
        }
        if(boardSize == 3){
            size = 30;
        }
        if(boardSize == 4){
            size = 35;
        }
        String from = requestList.getSelectedValue().toString();
        if(from == null){
            from = requestList.getComponent(0).toString();
        }
        vcon.acceptInvite(from,size);
    }//GEN-LAST:event_acceptButtonActionPerformed
    
    /**
     * Calls the declineInvite method within the MatchmakingViewController
     * @param evt, when the decline button is chosen by the player.
     */
    private void declineLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineLabelActionPerformed
        String from = requestList.getSelectedValue().toString();
        if(from == null){
            from = requestList.getComponent(0).toString();
        }
        vcon.declineInvite(from);
    }//GEN-LAST:event_declineLabelActionPerformed

    private void boardSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardSizeComboBoxActionPerformed
        int boardSize = boardSizeComboBox.getSelectedIndex();
        if(boardSize == 0){
            size = 15;
        }
        if(boardSize == 1){
            size = 20;
        }
        if(boardSize == 2){
            size = 25;
        }
        if(boardSize == 3){
            size = 30;
        }
        if(boardSize == 4){
            size = 35;
        }
    }//GEN-LAST:event_boardSizeComboBoxActionPerformed
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JComboBox boardSizeComboBox;
    private javax.swing.JButton declineLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel matchmakingLabel;
    private javax.swing.JButton menuButton;
    private javax.swing.JList playerList;
    private javax.swing.JLabel playersOnlineLabel;
    private javax.swing.JList requestList;
    private javax.swing.JLabel requestsLabel;
    private javax.swing.JButton sendgameButton;
    // End of variables declaration//GEN-END:variables
}