package gomoku;

/**
 * This class displays the message depending on if the player won or lost.
 * The menu button redirects the user back to [][][][][]
 * 
 * NOTE: NOT FULLY IMPLEMENTED
 */
public class PostGameView extends javax.swing.JPanel {
    PostGameViewController vcon;
    
    /**
     * Constructor
     * Creates the PostGameView and initialize components
     * @param vc, the PostGameController
     */
    public PostGameView(PostGameViewController vc) {
        initComponents();
        vcon = vc;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winText = new javax.swing.JLabel();
        loseText = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        winText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        winText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winText.setText("You Win!!");

        loseText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loseText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loseText.setText("You Lose...");

        menuButton.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loseText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(winText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(winText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loseText)
                .addGap(27, 27, 27)
                .addComponent(menuButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Calls mainMenu from the PostGameViewController
     * @param evt, when the user selects the menu button
     */
    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        vcon.mainMenu();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loseText;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel winText;
    // End of variables declaration//GEN-END:variables
}