package gomoku;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PLUCSCE
 */
public class WinLossPopupView extends javax.swing.JPanel {
    GameViewController gvc;
    SignInViewController svc;
    
    /**
     * Creates new form WinLossPopupView
     */
    public WinLossPopupView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lossLabel = new javax.swing.JLabel();
        winLabel = new javax.swing.JLabel();
        mmButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lossLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lossLabel.setText("You Lose...");
        add(lossLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 37, 143, -1));

        winLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        winLabel.setText("You Win!!!!");
        add(winLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 77, -1, -1));

        mmButton.setText("Return to Matchmaking");
        mmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmButtonMouseClicked(evt);
            }
        });
        add(mmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 124, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmButtonMouseClicked
        //svc = new SignInViewController();
        svc.SendLoginRequest(svc.globalUser, svc.globalPassword); // go back to matchmaking
        gvc.hideView(); // hides game view and popup view
    }//GEN-LAST:event_mmButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lossLabel;
    private javax.swing.JButton mmButton;
    public javax.swing.JLabel winLabel;
    // End of variables declaration//GEN-END:variables
}
